version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Kiddicute
    ports:
      - '9500:9500'
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
